#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Solaar
Version  : 1.0.1
Release  : 15
URL      : https://github.com/pwr/Solaar/archive/1.0.1.tar.gz
Source0  : https://github.com/pwr/Solaar/archive/1.0.1.tar.gz
Summary  : Linux devices manager for the Logitech Unifying Receiver.
Group    : Development/Tools
License  : GPL-2.0
Requires: Solaar-bin = %{version}-%{release}
Requires: Solaar-license = %{version}-%{release}
Requires: Solaar-python = %{version}-%{release}
Requires: Solaar-python3 = %{version}-%{release}
Requires: pyudev
BuildRequires : buildreq-distutils3
BuildRequires : pyudev
BuildRequires : util-linux

%description
**Solaar** is a Linux device manager for Logitech's [Unifying][unifying] Receiver
peripherals. It is able to pair/unpair devices to the receiver, and for most
devices read battery status.

%package bin
Summary: bin components for the Solaar package.
Group: Binaries
Requires: Solaar-license = %{version}-%{release}

%description bin
bin components for the Solaar package.


%package extras
Summary: extras components for the Solaar package.
Group: Default

%description extras
extras components for the Solaar package.


%package license
Summary: license components for the Solaar package.
Group: Default

%description license
license components for the Solaar package.


%package python
Summary: python components for the Solaar package.
Group: Default
Requires: Solaar-python3 = %{version}-%{release}
Provides: solaar-python

%description python
python components for the Solaar package.


%package python3
Summary: python3 components for the Solaar package.
Group: Default
Requires: python3-core
Provides: pypi(solaar)
Requires: pypi(pyudev)

%description python3
python3 components for the Solaar package.


%prep
%setup -q -n Solaar-1.0.1
cd %{_builddir}/Solaar-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607992441
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Solaar
cp %{_builddir}/Solaar-1.0.1/COPYING %{buildroot}/usr/share/package-licenses/Solaar/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/Solaar-1.0.1/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/Solaar/addefb57a76bd4a61d61b57bf72a2bb44b096b60
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -Dm0644 rules.d/42-logitech-unify-permissions.rules %{buildroot}%/usr/lib/udev/rules.d/42-logitech-unify-permissions.rules
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/solaar-cli

%files extras
%defattr(-,root,root,-)
/usr/bin/solaar
/usr/lib/python3.9/site-packages/solaar/__pycache__/gtk.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__init__.py
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/about.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/action.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/icons.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/notify.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/pair_window.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/__pycache__/tray.cpython-39.pyc
/usr/lib/python3.9/site-packages/solaar/ui/about.py
/usr/lib/python3.9/site-packages/solaar/ui/action.py
/usr/lib/python3.9/site-packages/solaar/ui/config_panel.py
/usr/lib/python3.9/site-packages/solaar/ui/icons.py
/usr/lib/python3.9/site-packages/solaar/ui/notify.py
/usr/lib/python3.9/site-packages/solaar/ui/pair_window.py
/usr/lib/python3.9/site-packages/solaar/ui/tray.py
/usr/lib/python3.9/site-packages/solaar/ui/window.py
/usr/share/applications/solaar.desktop
/usr/share/icons/hicolor/scalable/apps/solaar.svg
/usr/share/solaar/icons/light_000.png
/usr/share/solaar/icons/light_020.png
/usr/share/solaar/icons/light_040.png
/usr/share/solaar/icons/light_060.png
/usr/share/solaar/icons/light_080.png
/usr/share/solaar/icons/light_100.png
/usr/share/solaar/icons/light_unknown.png
/usr/share/solaar/icons/solaar-attention.svg
/usr/share/solaar/icons/solaar-init.svg
/usr/share/solaar/icons/solaar.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Solaar/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/Solaar/addefb57a76bd4a61d61b57bf72a2bb44b096b60

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
